{
 "title": "Ktor Monitoring",
 "tags": [
  "Ktor",
  "REST"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_usage{instance=\"$instance\"}[1m])*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(system_cpu_usage{instance=\"$instance\"}[1m])*100"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Overall Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{status=~\"^2..$\", route!=\"/metrics\"})",
       "legendFormat": "2XX Success"
      }
     ]
    },
    {
     "title": "API Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{status=~\"^4..$\", route!=\"/metrics\"})",
       "legendFormat": "4XX Errors"
      }
     ]
    },
    {
     "title": "Server Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{status=~\"^5..$\", route!=\"/metrics\"})",
       "legendFormat": "5XX Errors"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{route!=\"/metrics\"})",
       "legendFormat": "Total requests"
      }
     ]
    },
    {
     "title": "Average Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(ktor_http_server_requests_seconds{route!=\"/metrics\"}[1m]))",
       "legendFormat": "Response time"
      }
     ]
    },
    {
     "title": "Requests per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(ktor_http_server_requests_seconds_count{route!=\"/metrics\"}[1m]))",
       "legendFormat": "Total requests (min)"
      }
     ]
    },
    {
     "title": "Top 10 APIs",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(9, sort_desc(sum by(route, method) (ktor_http_server_requests_seconds_count{route!=\"/metrics\"})))",
       "legendFormat": "{{method}}  {{route}}"
      }
     ]
    },
    {
     "title": "Errors by API",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{route!=\"/metrics\", status=\"^4..$\"})))",
       "legendFormat": "{{method}} {{route}} {{status}}"
      }
     ]
    },
    {
     "title": "Errors by Server",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{route!=\"/metrics\", status=\"^5..$\"})))",
       "legendFormat": "{{method}} {{route}} {{status}}"
      }
     ]
    },
    {
     "title": "Response time of 95% of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ktor_http_server_requests_seconds{route!=\"/metrics\", quantile=\"0.95\"}",
       "legendFormat": "{{method}} {{route}} 95%"
      }
     ]
    },
    {
     "title": "Response time of 90% of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ktor_http_server_requests_seconds{route!=\"/metrics\", quantile=\"0.9\"}",
       "legendFormat": "{{method}} {{route}} 95%"
      }
     ]
    },
    {
     "title": "Response time of 50% of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ktor_http_server_requests_seconds{route!=\"/metrics\", quantile=\"0.5\"}",
       "legendFormat": "{{method}} {{route}} 50%"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{status=~\"^2..$\", route!=\"/metrics\", instance=\"$instance\"})",
       "legendFormat": "2XX Success"
      }
     ]
    },
    {
     "title": "API Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{status=~\"^4..$\", route!=\"/metrics\", instance=\"$instance\"})",
       "legendFormat": "4XX Errors"
      }
     ]
    },
    {
     "title": "Server Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{status=~\"^5..$\", route!=\"/metrics\", instance=\"$instance\"})",
       "legendFormat": "5XX Errors"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ktor_http_server_requests_seconds_count{route!=\"/metrics\", instance=\"$instance\"})",
       "legendFormat": "Total requests"
      }
     ]
    },
    {
     "title": "Average Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(ktor_http_server_requests_seconds{route!=\"/metrics\", instance=\"$instance\"}[1m]))",
       "legendFormat": "Response time"
      }
     ]
    },
    {
     "title": "Requests per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(ktor_http_server_requests_seconds_count{route!=\"/metrics\", instance=\"$instance\"}[1m]))",
       "legendFormat": "Total requests (min)"
      }
     ]
    },
    {
     "title": "Top 10 APIs",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(9, sort_desc(sum by(route, method) (ktor_http_server_requests_seconds_count{instance=\"$instance\", route!=\"/metrics\"})))",
       "legendFormat": "{{method}}  {{route}}"
      }
     ]
    },
    {
     "title": "Errors by API",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{instance=\"$instance\", route!=\"/metrics\", status=\"^4..$\"})))",
       "legendFormat": "{{method}} {{route}} {{status}}"
      }
     ]
    },
    {
     "title": "Errors by Server",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{instance=\"$instance\", route!=\"/metrics\", status=\"^5..$\"})))",
       "legendFormat": "{{method}} {{route}} {{status}}"
      }
     ]
    },
    {
     "title": "Response time of 95% of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/metrics\", quantile=\"0.95\"}",
       "legendFormat": "{{method}} {{route}} 95%"
      }
     ]
    },
    {
     "title": "Response time of 90% of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/metrics\", quantile=\"0.9\"}",
       "legendFormat": "{{method}} {{route}} 95%"
      }
     ]
    },
    {
     "title": "Response time of 50% of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/metrics\", quantile=\"0.5\"}",
       "legendFormat": "{{method}} {{route}} 50%"
      }
     ]
    }
   ]
  }
 ]
}