{
 "title": "Windows Exporter",
 "tags": [
  "windows",
  "windows_exporter",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "label": "windows_exporter location", "query": "host.docker.internal:9182" }
  ]
 },
 "panels": [
  { "title": "Host overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General information",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "windows_os_info * on(instance) group_right(product) windows_cs_hostname"
    },
    {},
    {}
   ]
  },
  {
   "title": "Disk (free)",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "repeat": "host",
   "targets": [
    {
     "expr": "sort_desc(windows_logical_disk_free_bytes{instance=~\"$host\",volume=~\"(^[A-Z]:$)\"})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes / windows_logical_disk_size_bytes)*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "repeat": "host",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_os_time{instance=~\"$host\"} - windows_system_system_up_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "format": "rothz",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 5 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_logical_processors{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(irate(windows_cpu_time_total{instance=~\"$host\", mode=\"idle\"}[5m])) > 0"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) > 0"
    }
   ]
  },
  {
   "title": "Net IN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{instance=~\"$host\"}[10m]))"
    }
   ]
  },
  {
   "title": "Net OUT",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{instance=~\"$host\"}[10m]))"
    }
   ]
  },
  { "title": "CPU details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "repeat": "host",
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(windows_cpu_time_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System exceptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_system_exception_dispatches_total{instance=~\"$host\"}[5m])",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "System threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_system_threads{instance=~\"$host\"}",
     "legendFormat": "threads"
    }
   ]
  },
  { "title": "Memory details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Virtual"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Physical"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "irate(windows_net_bytes_received_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) > 0",
       "legendFormat": "Received"
      },
      {
       "expr": "-irate(windows_net_bytes_sent_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) < 0",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Network discarded/error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "repeat": "host",
     "yaxes": [
      { "format": "pps", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "irate(windows_net_packets_outbound_discarded{instance=~\"$host\",nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_outbound_errors{instance=~\"$host\"}[5m])",
       "legendFormat": "Sent ({{nic}})"
      },
      {
       "expr": "irate(windows_net_packets_received_discarded{instance=~\"$host\", nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_received_errors{instance=~\"$host\"}[5m])",
       "legendFormat": "Received ({{nic}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk (free)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "windows_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Disk activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(windows_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(windows_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(windows_logical_disk_write_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(windows_logical_disk_read_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    }
   ]
  }
 ]
}