version: '3.5'
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sine
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-sine:/data/postgres
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: sine
    ports:
      - '27017:27017'
    volumes:
      - mongo-sine:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo

  mongo-express:
    container_name: mongo-express
    restart: unless-stopped
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://admin:123@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo

  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.org
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  postgres-sine:
  mongo-sine:
  pgadmin:
