version: '3.5'
services:
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus
    ports:
      - '9090:9090'
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - monitoring
    extra_hosts:
      # requires Docker Engine >= 20.04 -> needed to access host to gather node metrics from exporters
      - "host.docker.internal:host-gateway"
    depends_on:
      - docker-volume-exporter
      - cadvisor

  grafana:
    container_name: grafana
    restart: unless-stopped
    build: ./grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    command: --housekeeping_interval=10s --disable_metrics=accelerator,advtcp,cpu_topology,diskIO,hugetlb,percpu,process,referenced_memory,resctrl,sched,tcp,udp --docker_only=true
    ports:
      - '8060:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  docker-volume-exporter:
    container_name: docker-volume-exporter
    restart: unless-stopped
    build: ./docker-volume-exporter
    ports:
      - '2112:2112'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge
