global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']
    params:
      collect[]:
        - cpu
        - cs
        - logical_disk
        - net
        - os
        - system
        - textfile
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'micrometer_0'
    static_configs:
      - targets: ['192.168.1.230:8070']
  - job_name: 'micrometer_1'
    static_configs:
      - targets: ['192.168.1.230:8071']
  - job_name: 'micrometer_2'
    static_configs:
      - targets: ['192.168.1.230:8072']
  - job_name: 'micrometer_3'
    static_configs:
      - targets: ['192.168.1.230:8073']
#  - job_name: 'micrometer_4'
#    static_configs:
#      - targets: ['192.168.1.230:8074']
#  - job_name: 'micrometer_5'
#    static_configs:
#      - targets: ['192.168.1.230:8075']
#  - job_name: 'micrometer_6'
#    static_configs:
#      - targets: ['192.168.1.230:8076']
#  - job_name: 'micrometer_7'
#    static_configs:
#      - targets: ['192.168.1.230:8077']
