global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']
    params:
      collect[]:
        - cpu
        - cs
        - logical_disk
        - net
        - os
        - system
        - textfile
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'sine_wave_0'
    static_configs:
      - targets: ['host.docker.internal:8070']
  - job_name: 'sine_wave_1'
    static_configs:
      - targets: ['host.docker.internal:8071']
  - job_name: 'sine_wave_2'
    static_configs:
      - targets: ['host.docker.internal:8072']
  - job_name: 'sine_wave_3'
    static_configs:
      - targets: ['host.docker.internal:8073']
#  - job_name: 'sine_wave_4'
#    static_configs:
#      - targets: ['host.docker.internal:8074']
#  - job_name: 'sine_wave_5'
#    static_configs:
#      - targets: ['host.docker.internal:8075']
#  - job_name: 'sine_wave_6'
#    static_configs:
#      - targets: ['host.docker.internal:8076']
#  - job_name: 'sine_wave_7'
#    static_configs:
#      - targets: ['host.docker.internal:8077']
