# config file version
apiVersion: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  - name: Prometheus
    type: prometheus
    access: server
    url: http://prometheus:9090
    isDefault: true
